In [1]:
import json
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import SGD,Adam
from tensorflow.keras.layers import Embedding, LSTM, Dense

# Load intents data from JSON file
with open('intents.json') as file:
    data = json.load(file)

# Extract messages and labels from the dataset
messages = []
labels = []
for intent in data['intents']:
    for pattern in intent['patterns']:
        messages.append(pattern)
        labels.append(intent['tag'])

# Tokenize messages
tokenizer = Tokenizer()
tokenizer.fit_on_texts(messages)
vocab_size = len(tokenizer.word_index) + 1

# Convert messages to sequences of tokens
sequences = tokenizer.texts_to_sequences(messages)

# Pad sequences to ensure uniform length
max_sequence_length = max(len(seq) for seq in sequences)
padded_sequences = pad_sequences(sequences, maxlen=max_sequence_length, padding='post')

# Convert labels to one-hot encoding
label_set = set(labels)
label_indices = {label: i for i, label in enumerate(label_set)}
num_classes = len(label_set)
encoded_labels = [label_indices[label] for label in labels]

# Define and compile the model
model = Sequential([
    Embedding(vocab_size, 300, input_length=max_sequence_length),
    LSTM(256),
    Dense(num_classes, activation='softmax')
])
sgd = SGD(learning_rate=0.00000001, decay=1e-6, momentum=0.9, nesterov=True)
adam=Adam()
model.compile(loss='categorical_crossentropy', optimizer=adam, metrics=['accuracy'])
encoded_labels=np.array(encoded_labels)
from keras.utils import to_categorical
encoded_labels=to_categorical(encoded_labels)


c:\Users\HP\Documents\python\Lib\site-packages\keras\src\layers\core\embedding.py:86: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
c:\Users\HP\Documents\python\Lib\site-packages\keras\src\optimizers\base_optimizer.py:34: UserWarning: Argument `decay` is no longer supported and will be ignored.
  warnings.warn(


In [2]:
# Train the model
model.fit(padded_sequences,encoded_labels , epochs=200, batch_size=16, validation_split=0.2)

# Save the model for future use


Epoch 1/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 3s 39ms/step - accuracy: 0.0211 - loss: 4.7835 - val_accuracy: 0.0000e+00 - val_loss: 6.1486
Epoch 2/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.0706 - loss: 4.1357 - val_accuracy: 0.0000e+00 - val_loss: 5.9526
Epoch 3/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.0344 - loss: 4.0698 - val_accuracy: 0.0000e+00 - val_loss: 7.2331
Epoch 4/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.1106 - loss: 3.8528 - val_accuracy: 0.0000e+00 - val_loss: 6.0174
Epoch 5/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.0774 - loss: 3.8567 - val_accuracy: 0.0000e+00 - val_loss: 6.6728
Epoch 6/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.0537 - loss: 3.6418 - val_accuracy: 0.0000e+00 - val_loss: 7.2923
Epoch 7/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.1093 - loss: 3.4771 - val_accuracy: 0.0000e+00 - val_loss: 8.7774
Epoch 8/200
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.0827 - los

In [3]:
model.save('intent_classification_model.keras')
print(encoded_labels,encoded_labels.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] (283, 129)
